if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# GPG signing
export GPG_TTY=$(tty)

export TIMEZONE="Europe/Dublin"
export TZ="Europe/Dublin"
export EDITOR=nvim
export FZF_DEFAULT_OPTS="--ansi"
export FZF_DEFAULT_COMMAND="fdfind --type file --color=always --follow --hidden --exclude .git"
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_ALT_C_COMMAND="fdfind --type directory --color=always --follow --hidden --exclude .git"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {}'"

[ -f "${HOME}/.fzf.bash" ] && source "${HOME}/.fzf.bash"

# use new auth plugin for gke
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Most boxes I work on have about 16 cores.
# See: https://github.com/golang/go/issues/33803
export GOMAXPROCS=16
export SRC_DIR="${HOME}/src"
export GOPATH="${HOME}/go"
export PATH="${PATH}:${HOME}/bin:${GOPATH}/bin:/usr/local/go/bin:${PATH}"

source ~/.bash_aliases

export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

complete -F __start_kubectl k

POWERLINEGO=$(command -v powerline-go)

function _update_ps1() {
    PS1="$($POWERLINEGO -newline -error $? -colorize-hostname -mode patched -jobs $(jobs -p | wc -l))"
}

if [ "$TERM" != "linux" ] && [ -f "${POWERLINEGO}" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

complete -C '/usr/bin/aws_completer' aws
