# shellcheck shell=bash
# shellcheck disable=SC2296,SC2298,SC2139
# If you come from bash you might have to change your $PATH.
export PATH=/opt/homebrew/opt/coreutils/libexec/gnubin:$HOME/bin:${HOME}/go/bin:/opt/homebrew/bin:$PATH

function powerline_precmd() {
    PS1="$(powerline-go -error $? -jobs ${${(%):%j}:-0})"

    # Uncomment the following line to automatically clear errors after showing
    # them once. This not only clears the error for powerline-go, but also for
    # everything else you run in that shell. Don't enable this if you're not
    # sure this is what you want.

    #set "?"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ] && command -v powerline-go >/dev/null; then
    install_powerline_precmd
fi

export EDITOR='nvim'
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "$OS" = "darwin" ]; then
    export DOCKER_HOST='unix:///Users/cian/.colima/default/docker.sock'
fi

alias zshconfig="${EDITOR} ~/.zshrc"
autoload -Uz compinit && compinit

